/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Headphone.glb --transform --keepmeshes --R 2048 
Files: public/Headphone.glb [5.48MB] > C:\Users\danie\OneDrive\Documents\GitHub\headset_3d_configration\Headphone_Configrator\Headphone-transformed.glb [733.02KB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from 'valtio'
import { state } from './Store'
import { useFrame } from '@react-three/fiber'

export function Headphone(props) {

  const meshref = useRef()

  const snap = useSnapshot(state)
  const { nodes, materials } = useGLTF('/Headphone-transformed.glb')


  useFrame(()=>{
    meshref.current.position.x= state.headphonex
     meshref.current.position.y= state.headphoney

    meshref.current.rotation.y= state.rotationY
    const targetscale=state.headphonescale
    meshref.current.scale.set(targetscale, targetscale, targetscale)
  })


  return (
    <group ref={meshref}  {...props} dispose={null}>
<mesh geometry={nodes.ear_cushion_Baked.geometry}>
  
  <primitive
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
color={snap.colors.cushion} />

</mesh>
      <mesh geometry={nodes.earcup_Baked.geometry} material={materials['MergedBake_Baked.008']}  > 
          <primitive 
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
    color={snap.colors.cups} // Or use '#ff0000' with all 6 digits!
  />

</mesh>
      <mesh geometry={nodes.headband_cushion_Baked.geometry} material={materials['MergedBake_Baked.008']} >
  <primitive 
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
color={snap.colors.cushion}   />

</mesh>
      <mesh geometry={nodes.headband_top_Baked.geometry} material={materials['MergedBake_Baked.008']} position={[0.125, 2.483, -0.202]} >
     <primitive 
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
color={snap.colors.cups}   />

</mesh>
      <mesh geometry={nodes.holder_Baked.geometry} material={materials['MergedBake_Baked.008']} >
          <primitive 
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
    color={snap.colors.cushion} // Or use '#ff0000' with all 6 digits!
  />

</mesh>
      <mesh geometry={nodes.insidespeacker_Baked.geometry} material={materials['MergedBake_Baked.008']} >
      <primitive 
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
color={snap.colors.cushion}   />

</mesh>
      <mesh geometry={nodes.middle_Baked.geometry} material={materials['MergedBake_Baked.008']} >
          <primitive 
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
color={snap.colors.cups} 
  />

</mesh>
      <mesh geometry={nodes.outerspeacker_Baked.geometry} material={materials['MergedBake_Baked.008']} >  <primitive 
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
    color="black" // Or use '#ff0000' with all 6 digits!
  />

</mesh>
      <mesh geometry={nodes.slider_Baked.geometry} material={materials['MergedBake_Baked.008']} >
       <primitive 
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
color={snap.colors.slider}   />

</mesh>
      <mesh geometry={nodes.volume_Baked.geometry} material={materials['MergedBake_Baked.008']} >
          <primitive 
    object={materials['MergedBake_Baked.008'].clone()} 
    attach="material" 
    color="white" // Or use '#ff0000' with all 6 digits!
  />

</mesh>
    </group>
  )
}

useGLTF.preload('/Headphone-transformed.glb')
